### ISSUE TITLE
Compile C# modules ahead of time

### ISSUE THREAD

**Issue by MatejKafka** [mkht/DSCR_Shortcut#14]
Hi, is it possible to pre-compile the ShellLink.cs and VKeyUtil.cs into a .dll? Currently, this module takes about 800 ms to load on my machine, which is quite slow.

It should be enough to just target netstandard2.0 and import the .dll instead of using `Add-Type`. Everything should work exactly as now, just with faster startup.

I can do a PR if you're ok with that.

**Comment by mkht** [comment]
On my laptop it loads in about 300ms, 800ms is certainly slow.
I will try precompiling to see how much faster it gets.

**Comment by mkht** [comment]
In early tests, precompiling resulted in 3-5 times faster module loading times.
On my laptop it loaded in less than 100ms.

Please give me a little more time to test as I need to make sure each function works correctly.

**Comment by mkht** [comment]
Since the test results were good, we have released it as v2.3.0. Please try it out. 😃
